@startuml
!include style.puml
!pragma layout smetana
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PatientListPanel
Class PatientCard
Class StatusBarFooter
Class CommandBox
Class MedicalHistoryPanel
Class MedicalHistoryCard
Class AppointmentPanel
Class AppointmentCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PatientListPanel
MainWindow *-down-> "1" AppointmentPanel
MainWindow *-down-> "1" MedicalHistoryPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

PatientListPanel -down-> "*" PatientCard
AppointmentPanel -down-> "*" AppointmentCard
MedicalHistoryPanel -down-> "*" MedicalHistoryCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PatientListPanel --|> UiPart
PatientCard --|> UiPart
AppointmentPanel --|> UiPart
AppointmentCard --|> UiPart
MedicalHistoryPanel --|> UiPart
MedicalHistoryCard --|> UiPart


StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

PatientCard ..> Model
AppointmentCard ..> Model
MedicalHistoryCard ..> Model

UiManager -right-> Logic
MainWindow -left-> Logic

PatientListPanel -[hidden]left- HelpWindow
AppointmentPanel -[hidden]left- HelpWindow
MedicalHistoryPanel -[hidden]left- HelpWindow

HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter


MainWindow -[hidden]-|> UiPart
@enduml