@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package States {
    class State1 as "<u>ab0:ClinicBook</u>"
}

class Pointer as "Current State" #FFFFFF
Pointer -up-> State1

hide State2
hide State3
@enduml
