@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 5"

package States <<rectangle>> {
    class "<u>ab0:ClinicBook</u>" as State1
    class "<u>ab1:ClinicBook</u>" as State2
}

State1 -[hidden]right-> State2

hide "<u>ab2:ClinicBook</u>"

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
